name: 更新配置文件

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update -y
        sudo -E apt-get -qq install -y gawk git gettext libssl-dev xsltproc zip git-core wget curl grep python2.7 python3 python3-pip libpython3-dev
        sudo timedatectl set-timezone "Asia/Shanghai"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
          
    - name: Clone source code
      env: 
        REPO_URL: https://github.com/immortalwrt/immortalwrt
        REPO_BRANCH: openwrt-24.10
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
          
    - name: Update & Install feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        ./scripts/feeds install -a
          
    - name: Configuration Customization - Build_x86_64
      env:
        CONFIG_FILE: '.config'
      run: |
        chmod +x ./customize.sh && ./customize.sh
        cd openwrt && make defconfig
          
    - name: SSH
      uses: csexton/debugger-action@master
   
    - name: Update Configuration
      env:
        CONFIG_FILE: '.config'
      run: |
        cd openwrt
        make defconfig
        ./scripts/diffconfig.sh > ${GITHUB_WORKSPACE}/$CONFIG_FILE
          
    - name: Upload Configuratio
      env:
        CONFIG_FILE: '.config'
      run: |
        git config --global user.email "FengWuDeLangHua@users.noreply.github.com"
        git config --global user.name "FengWuDeLangHua"
        git clone https://user:${{ secrets.REPO_TOKEN }}@github.com/${{github.repository}}.git UPLOAD
        cd UPLOAD
        if [[ -n "$(ls -A "$CONFIG_FILE" 2>/dev/null)" ]]; then
          git rm -rf $CONFIG_FILE
        fi
        cp -Rf $GITHUB_WORKSPACE/$CONFIG_FILE $CONFIG_FILE
        git add .
        git commit -m "编译OpenWrt"
        git push --force "https://${{ secrets.REPO_TOKEN }}@github.com/${{github.repository}}" HEAD:main
