name: 更新配置文件

on:
  workflow_dispatch:

env:
#   REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: master
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  TZ: Asia/Shanghai
  
jobs:
  updata-config:
    runs-on: ubuntu-latest
    
    steps:
      - name: 初始化
        uses: actions/checkout@main

      - name: 安装编译环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          git config --global user.email "FengWuDeLangHua@users.noreply.github.com"
          git config --global user.name "FengWuDeLangHua"
          
      - name: 下载源码
        working-directory: /workdir
        run: |
          git clone $REPO_URL -b $REPO_BRANCH openwrt
          ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
          
      - name: 加载自定义文件
        run: |
          chmod +x $DIY_P1_SH
          cd openwrt
          $GITHUB_WORKSPACE/$DIY_P1_SH
          
      - name: 更新自定义文件
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
      - name: 加载自定义设置
        run: |
          chmod +x $DIY_P2_SH
          cd openwrt
          $GITHUB_WORKSPACE/$DIY_P2_SH
          
      - name: SSH链接
        uses: P3TERX/ssh2actions@main
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          
      - name: 更新配置文件
        run: |
          cd openwrt
          make defconfig
          ./scripts/diffconfig.sh > ${GITHUB_WORKSPACE}/${CONFIG_FILE}
          
      - name: 上传配置文件
        run: |
          git clone -b main https://github.com/${{github.repository}}.git repo
          cd repo
          if [[ -n "$(ls -A "${CONFIG_FILE}" 2>/dev/null)" ]]; then
            git rm -rf ${CONFIG_FILE}
          fi
          cp -Rf $GITHUB_WORKSPACE/${CONFIG_FILE} ${CONFIG_FILE}
          git add .
          git commit -m "$config updata"
          git push --force "https://${{ secrets.REPO_TOKEN }}@github.com/${{github.repository}}" HEAD:main
