name: 更新配置文件

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: 安装编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        curl -s https://build-scripts.immortalwrt.eu.org/init_build_environment.sh | sudo bash
        sudo timedatectl set-timezone "Asia/Shanghai"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
          
    - name: Clone source code
      env: 
        REPO_URL: https://github.com/coolsnowwolf/lede
        REPO_BRANCH: master
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        echo "src-git ssrp https://github.com/fw876/helloworld.git" >> ./feeds.conf.default
          
    - name: Update & Install feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        ./scripts/feeds install -a
          
    - name: Configuration Customization - Build_x86_64
      env:
        CONFIG_FILE: 'x86_64.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x ./customize.sh && ./customize.sh
        cd openwrt && make defconfig
          
    - name: SSH
      uses: danshui-git/debugger-action@main
   
    - name: Update Configuration
      run: |
        cd openwrt
        make defconfig
        ./scripts/diffconfig.sh > ${GITHUB_WORKSPACE}/${CONFIG_FILE}
          
    - name: Upload Configuratio
      run: |
        git clone -b main https://github.com/${{github.repository}}.git repo
        cd repo
        if [[ -n "$(ls -A "${CONFIG_FILE}" 2>/dev/null)" ]]; then
          git rm -rf ${CONFIG_FILE}
        fi
        cp -Rf $GITHUB_WORKSPACE/${CONFIG_FILE} ${CONFIG_FILE}
        git add .
        git commit -m "编译OpenWrt"
        git push --force "https://${{ secrets.REPO_TOKEN }}@github.com/${{github.repository}}" HEAD:main
