name: 更新配置文件

on:
  workflow_dispatch:
    inputs:
      SSH_ACTION:
        description: 'SSH远程配置固件'
        required: false
        default: 'true'
        type: boolean
        
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /etc/mysql /etc/php
        sudo -E apt-get -y purge azure-cli* docker* ghc* zulu* hhvm* llvm* firefox* google* dotnet* aspnetcore* powershell* openjdk* adoptopenjdk* mysql* php* mongodb* moby* snap* || true
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install libfuse-dev $(curl -fsSL git.io/depends-ubuntu-2204)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "Asia/Shanghai"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
          
    - name: Clone source code
      env: 
        REPO_URL: https://github.com/coolsnowwolf/lede
        REPO_BRANCH: master
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
          
    - name: Update & Install feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        ./scripts/feeds install -a
          
    - name: Configuration Customization - Build_x86_64
      env:
        CONFIG_FILE: '.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x ./customize.sh && ./customize.sh
        cd openwrt && make defconfig
          
    - name: SSH
      if: env.SSH_ACTION == 'true'
      # uses: danshui-git/debugger-action@main
      uses: csexton/debugger-action@master
   
    - name: Update Configuration
      env:
        CONFIG_FILE: '.config'
      run: |
        cd openwrt
        make defconfig
        ./scripts/diffconfig.sh > ${GITHUB_WORKSPACE}/$CONFIG_FILE
          
    - name: Upload Configuratio
      env:
        CONFIG_FILE: '.config'
      run: |
        git config --global user.email "FengWuDeLangHua@users.noreply.github.com"
        git config --global user.name "FengWuDeLangHua"
        git clone https://user:${{ secrets.REPO_TOKEN }}@github.com/${{github.repository}}.git UPLOAD
        cd UPLOAD
        if [[ -n "$(ls -A "$CONFIG_FILE" 2>/dev/null)" ]]; then
          git rm -rf $CONFIG_FILE
        fi
        cp -Rf $GITHUB_WORKSPACE/$CONFIG_FILE $CONFIG_FILE
        git add .
        git commit -m "编译OpenWrt"
        git push --force "https://${{ secrets.REPO_TOKEN }}@github.com/${{github.repository}}" HEAD:main
